ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
      args: [--line-length=120]
      language_version: python3
      exclude: 
        (?x)(
          ^.devcontainer/configuration/|
          ^src/netbox_contract/migrations/
        )
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      exclude: 
        (?x)(
          ^.devcontainer/configuration/|
          ^src/netbox_contract/migrations/
        )

-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        stages: [manual]
